### PR TITLE
Awesome books with ES6

### PR DESCRIPTION
**Pull request by piesieomane**
In this PR, the following were implemented:-

- No linter errors
- Used correct GitHub flow
- Used ES6 functions
- Used modules to separate business logic and display

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @piesieomane, This is @sja-thedude your code reviewer.

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ Professional Readme
✔️ Correct git-flow
✔️ All linters passing

## Required 
- [ ] Kindly make sure your app works correctly. Currently, your app doesn't let me add or remove an item.
- [ ] Kindly display the date with luxon on the right side below the navigation bar.

https://user-images.githubusercontent.com/70269507/177197648-29e2be55-6f73-4d9d-8d74-2ce54ccdab9f.mov

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by piesieomane** [comment]
@sja-thedude Thank you very much for the review, but the work runs perfectly on `Brave browser`

**Review by bimbolabuari — COMMENTED** [review]
Hello @piesieomane 👋,

_This is an additional review as a result of the second opinion request._

- I check your project and it works fine 👍 

image

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away 🙂 

Keep rocking 🚀!

**Review by mikethreels — APPROVED** [review]
Hi Piesie, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by piesieomane** [comment]
@bimbolabuari Thank you very much, the other code reviewer just stressed me out

**Pull request merged**
